const config = require("../../../config.js");
const uid = require(config.HELPERS + "/uid.js");

const planets = [
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Ceres",
    "Pluto",
    "Haumea",
    "Makemake",
    "Eris",
    "Io",
    "Europa",
    "Ganymede",
    "Callisto",
    "Enceladus",
    "Titan",
    "Triton",
    "Dione",
    "Rhea",
    "Oberon",
    "Miranda",
    "Ariel",
    "Titania",
    "Umbriel",
    "Charon",
    "Phobos",
    "Deimos",
    "Vesta",
    "Pallas",
    "Hygiea",
    "Juno",
    "Egeria",
    "Davida",
    "Eunomia",
    "Iris",
    "Herculina",
    "Metis",
    "Hektor",
    "Ida",
    "Lutetia",
    "Psyche",
    "Kleopatra",
    "Eros",
    "Gaspra",
    "Mathilde",
    "Kalliope",
    "Themis",
    "Euphrosyne",
    "Sylvia",
    "Orpheus",
    "Bamberga",
    "Lutetia",
    "Doris",
    "Lucina",
    "Fortuna",
    "Euphrosyne",
    "Eugenia",
    "Cybele",
    "Pandora",
    "Prometheus",
    "Atlas",
    "Calypso",
    "Pan",
    "Janus",
    "Epimetheus",
    "Helene",
    "Narvi",
    "Methone",
    "Anthe",
    "Polydeuces",
    "Telesto",
    "Calypso",
    "Siarnaq",
    "Albiorix",
    "Paaliaq",
    "Skathi",
    "Erriapus",
    "Tarvos",
    "Kiviuq",
    "Ijiraq",
    "Phoebe",
    "Janus",
    "Epimetheus",
    "Pandora",
    "Pan"
];

const solarSystems = [
    "Kepler",
    "TRAPPIST",
    "Gliese",
    "Kepler",
    "HD",
    "WASP",
    "OGLE",
    "Cancri",
    "Tau Ceti",
];

const suns = [
    "Alpha Centauri A",
    "Alpha Centauri B",
    "Sirius",
    "Vega",
    "Betelgeuse",
    "Rigel",
    "Polaris",
    "Procyon",
    "Deneb",
    "Aldebaran",
    "Antares",
    "Arcturus",
    "Capella",
    "Castor",
    "Pollux",
    "Regulus",
    "Spica",
    "Altair",
    "Achernar",
    "Fomalhaut",
    "Bellatrix",
    "Elnath",
    "Dubhe",
    "Mizar",
    "Alioth",
    "Alkaid",
    "Mira",
    "Pleiades",
    "Alnilam",
    "Saiph",
    "Mintaka",
    "Denebola",
    "Gacrux",
    "Becrux",
    "Miaplacidus",
    "Acrux",
    "Alphard",
    "Nunki",
    "Sadalsuud",
    "Wezen",
    "Mirfak",
    "Hamal",
    "Diphda",
    "Menkalinan",
    "Algol",
    "Zubeneschamali",
    "Scheat",
    "Markab",
    "Malkuth",
    "Enif",
    "Ankaa",
    "Alderamin",
    "Sadr",
    "Tarazed",
    "Atria",
    "Peacock",
    "Naos",
    "Rasalhague",
    "Shaula",
    "Kaus Australis",
    "Kaus Borealis",
    "Nashira",
    "Rasalgethi",
    "Sabik",
    "Vindemiatrix",
    "Spica",
    "Gienah",
    "Sulafat",
    "Nash",
    "Sargas",
    "Izar",
    "Algieba",
    "Markeb",
    "Nair al Saif",
    "Al Niyat",
    "Sheliak",
    "Ruchbah",
    "Scheat",
    "Al Genib",
    "Acamar",
    "Matar",
    "Sadachbia",
    "Kornephoros",
    "Segin",
    "Homam",
    "Ancha",
    "Kaffaljidhma",
    "Nusakan",
    "Alrescha",
    "Alderamin",
    "Achird",
    "Etamin",
    "Albireo",
    "Izar",
    "Alphecca",
    "Eltanin",
    "Rasalhague",
    "Eps Indi",
    "Epsilon Eridani",
    "61 Cygni",
    "40 Eridani A",
    "70 Ophiuchi A",
    "Delta Pavonis"
];

const asteroids = [
    "Ceres",
    "Vesta",
    "Pallas",
    "Hygiea",
    "Juno",
    "Eunomia",
    "Davida",
    "Iris",
    "Herculina",
    "Metis",
    "Hektor",
    "Ida",
    "Lutetia",
    "Psyche",
    "Kleopatra",
    "Eros",
    "Gaspra",
    "Mathilde",
    "Kalliope",
    "Themis",
    "Euphrosyne",
    "Sylvia",
    "Orpheus",
    "Bamberga",
    "Doris",
    "Lucina",
    "Fortuna",
    "Euphrosyne",
    "Eugenia",
    "Cybele",
    "Pandora",
    "Prometheus",
    "Atlas",
    "Calypso",
    "Pan",
    "Janus",
    "Epimetheus",
    "Helene",
    "Narvi",
    "Methone",
    "Anthe",
    "Polydeuces",
    "Telesto",
    "Calypso",
    "Siarnaq",
    "Albiorix",
    "Paaliaq",
    "Skathi",
    "Erriapus",
    "Tarvos",
    "Kiviuq",
    "Ijiraq",
    "Phoebe",
    "Prometheus",
    "Epimetheus",
    "Pandora",
    "Helene",
    "Atlas",
    "Prometheus",
    "Epimetheus",
    "Pandora",
    "Calypso",
    "Siarnaq",
    "Albiorix",
    "Paaliaq",
    "Skathi",
    "Erriapus",
    "Tarvos",
    "Kiviuq",
    "Ijiraq",
    "Phoebe",
    "Eirene",
    "Galatea",
    "Aegaeon",
    "Jarnsaxa",
    "Narvi",
    "Greip",
    "Tarqeq",
    "Ymir",
    "Mundilfari",
    "Bergelmir",
    "Narvi",
    "Fornjot",
    "Kari",
    "Skoll",
    "Loge",
    "Aegir",
    "Bebhionn",
    "Bergelmir",
    "Bestla",
    "Farbauti",
    "Fenrir",
    "Fornjot",
    "Greip",
    "Hati",
    "Hyrrokkin",
    "Jarnsaxa",
    "Kari",
    "Kari",
    "Loge",
    "Siarnaq",
    "Tarqeq",
    "Ymir"
  ];

const blackHoles = [
    "Singularity X",
    "DarkStar Alpha",
    "Abyssal Void Zeta",
    "Cosmic Abyss Theta",
    "Eternal Darkness Omega",
    "Event Horizon Sigma",
    "Graviton Anomaly",
    "Quasar's Heart",
    "Supernova's End",
    "Phantom Singularity",
    "Vortex of Shadows",
    "Infinite Darkness",
    "The Unseen",
    "Stellar Oblivion",
    "Nebula's Core",
    "Celestial Rift",
    "Galactic Abyss",
    "Void of Eternity",
    "The Black Star",
    "Matter Devourer",
    "Gravity's Embrace",
    "The Abyssal Rift",
    "Singularity Omega",
    "Quasar's Embrace",
    "Eclipse of Time",
    "Void's Event Horizon"
  ];


const randomize = (arr) => {
    return arr[(Math.round(Math.random() * (arr.length - 1)))];
}

module.exports = (type) => {
    if (type == "planet") {
        return randomize(planets) + "-" + (uid.alphanum(Math.round(Math.random() * 2) + 1).toUpperCase());
    } else if (type == "space") {
        return randomize(solarSystems) + "-" + (uid.alphanum(Math.round(Math.random() * 2) + 1).toUpperCase());
    } else if (type == "asteroid") {
        return randomize(asteroids) + "-" + (uid.alphanum(Math.round(Math.random() * 2) + 1).toUpperCase());
    } else if (type == "sun") {
        return randomize(suns) + "-" + (uid.alphanum(Math.round(Math.random() * 2)  + 1).toUpperCase());
    } else if (type == "blackhole") {
        return randomize(blackHoles) + "-" + (uid.alphanum(Math.round(Math.random() * 2) + 1).toUpperCase());
    }
};